pipeline {
    agent any
    
    tools {
        nodejs 'nodejs'
    }

    stages {
        stage('Install') {
            steps {
                dir('atelier-pratique-pipeline') {
                    sh 'npm install'
                }
            }
        }
        stage('Build') {
            steps {
                dir('atelier-pratique-pipeline') {
                    sh 'npm run build'
                }
            }
        }
    }
}